version: '3.7'

services:
  idempiere:
    image: hummingbird9:latest
    environment:
      - DB_HOST=192.168.2.103
      - DB_PORT=5432
      - DB_NAME=KFSeed
      - DB_USER=adempiere
      - DB_PASS=adempiere
      - DB_ADMIN_PASS=postgres
    ports:
      - 8080:8080
      - 8443:8443
      - 12612:12612
    networks:
      - test

# volumes:
#   back-notused:
#   db-data:

networks:
  test:
    driver: bridge
