FROM postgres:15.5

# Environment variables for user and password
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Copy SQL script with commands
COPY init.sql /docker-entrypoint-initdb.d/

# Grant permissions to the script
RUN chmod +r /docker-entrypoint-initdb.d/init.sql
