#!/usr/bin/env bash

# chkconfig: 2345 20 80
# description: BlueCardinal Client

# Source function library.
. /etc/init.d/functions

SS_USER=sigmastream
BC_CLIENT_HOME=/home/sigmastream/bluecardinal/bluecardinal-webclient

getbluecardinalclientstatus(){
   pgrep -u sigmastream -f ${BC_CLIENT_HOME}
   BCCLIENTSTATUS=$?
}

case "$1" in 
start)
   getbluecardinalclientstatus
   if [ $BCCLIENTSTATUS -eq 0 ]; then
      echo "[!] BlueCardinal-WebClient is already running"
      exit 0
   fi
   ulimit -l unlimited
   if [ -n "$SS_USER" ];then 
      sudo chown -R $SS_USER:$SS_USER $BC_CLIENT_HOME/  > /dev/null 2>&1
      su $SS_USER -c "exec ${BC_CLIENT_HOME}/jre/bin/java -jar ${BC_CLIENT_HOME}/bluecardinal-client.jar --client-config=${BC_CLIENT_HOME}/config.xml 2>&1 & "
      sleep 2
      su $SS_USER -c "cd ${BC_CLIENT_HOME}/bluecardinal-ui/; exec ./run.sh 2>&1 &"
      echo "[+] BlueCardinal-WebClient is started."
   else
      exec ${BC_CLIENT_HOME}/jet-management-center.sh  2>&1 &
      exec sh ${BC_CLIENT_HOME}/bluecardinal-ui/run.sh 2>&1 &
   fi
   ;;
stop)
   getbluecardinalclientstatus
   if [ $BCCLIENTSTATUS -ne 0 ]; then
      echo "[#] BlueCardinal-WebClient is already stopped"
      exit 1
   fi
   pid=$(pgrep -f "${BC_CLIENT_HOME}" | tr '\n' ' ')
   su $SS_USER -c "kill -9 ${pid}"
   su $SS_USER -c "kill -9 ${pid}"
   su $SS_USER -c "pgrep -u sigmastream -f uvicorn | tr '\n' ' ' | xargs kill -9"
   echo "[+] BlueCardinal-WebClient is stopped."
   ;;
restart)
   $0 stop
   $0 start
   ;;

status)
   getbluecardinalclientstatus
   if [ $BCCLIENTSTATUS -eq 0 ]; then
      echo "[#] BlueCardinal-WebClient is running on pid=$(pgrep -f ${BC_CLIENT_HOME})"
      exit 0
   else
      echo "[#] BlueCardinal-WebClient is stopped."
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
