; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "RedCanary-Agent"
#define MyAppVersion "2.1.0"
#define MyAppPublisher "SigmaStream.LLC"
#define MyAppURL "http://www.sigmastream.com/"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
//Password=SigmaStream#1
AppId={{599E2CFF-B211-4BDD-B14A-14928E22C7F9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={sd}\SigmaStream\RedCanary\{#MyAppName}
//DisableDirPage=yes
DefaultGroupName={#MyAppName}
PrivilegesRequired=admin
DisableProgramGroupPage=yes
LicenseFile=D:\setups\scripts\SS_InstallerTerms.txt
OutputBaseFilename=RedCanary-Agent-20210816
OutputDir=D:\SigmaStream\Installers\RedCanary\Agent
SetupIconFile=D:\setups\scripts\redcanary-favicon.ico
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon=D:\setups\scripts\redcanary-favicon.ico

[Code]
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  { if we're on the directory selection page and the value returned by }
  { the WizardDirValue function contains at least one space, then... }
  if (CurPageID = wpSelectDir) and (Pos(' ', WizardDirValue) > 0) then
  begin
    Result := False;
    MsgBox('Target installation directory cannot contain spaces. ' +
      'Choose a different one.', mbError, MB_OK);
  end;
end;

////////////////////////////////////////////////////////////////////////////

// ADDING WARNING MESSAGE TO GENERATE LICENSE KEY FIRST.

////////////////////////////////////////////////////////////////////////////
[code]
function GetCustomSetupExitCode: Integer;
begin
  MsgBox('Please install RedCanary license key before starting RedCanary-Agent Service,In case of any query please write to "support@sigmastream.com".', mbInformation, MB_OK);
  Result := 0;
end;

////////////////////////////////////////////////////////////////////////////

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
//Source: "C:\RedCanary\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\setups\RedCanary\RedCanary-Agent\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
//Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\nssm.exe"; Parameters: "install RedCanary-Agent {app}\agent\start_agent.bat"
Filename: "{app}\nssm.exe"; Parameters: "set RedCanary-Agent Application {app}\agent\start_agent.bat"
Filename: "{app}\nssm.exe"; Parameters: "set RedCanary-Agent AppDirectory {app}\agent\"
Filename: "{app}\nssm.exe"; Parameters: "set RedCanary-Agent DisplayName RedCanary-Agent"
Filename: "{app}\nssm.exe"; Parameters: "set RedCanary-Agent Description RedCanary-Agent-Service"
Filename: "{app}\nssm.exe"; Parameters: "set RedCanary-Agent Start SERVICE_AUTO_START"
Filename: "{app}\generate-keycode.bat"; Flags: nowait runhidden postinstall
//Filename: "{app}\install-rcagent-64bit.bat"; Parameters: "install"; Flags: runhidden
//Filename: "{app}\start-rcagent.bat"; Parameters: "install"; Flags: runhidden
//Filename: "http://localhost:8099/"; Flags: shellexec runasoriginaluser

[UninstallRun]
Filename: {sys}\sc.exe; Parameters: "stop RedCanary-Agent" ; Flags: runhidden
Filename: {sys}\sc.exe; Parameters: "delete RedCanary-Agent" ; Flags: runhidden

