#!/bin/bash
YHSERVERHOME=/home/sigmastream/yhserver
YHWEBCLIENTHOME=/home/sigmastream/yhwebclient
RCAGENTHOME=/home/sigmastream/rcagent
RCSERVERHOME=/home/sigmastream/rcserver
BCHOME=/home/sigmastream/bcserver
DESTDIR=/home/sigmastream/Tools/Troubleshooting
DATETIME=$(echo $(date +%Y%m%d-%H%M%S))

yellowhammer() {
    if [ -d "${YHSERVERHOME}" ] && [ -d "${YHWEBCLIENTHOME}" ] ;then 
        if [ ! -d ${DESTDIR} ]; then
            mkdir -p ${DESTDIR} > /dev/null 2>&1
        fi
        sudo chown -R sigmastream:sigmastream ${DESTDIR}
        echo "[+] Collecting YellowHammer-Server files"
        sudo -u sigmastream mkdir -p ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/
        cd ${YHSERVERHOME} || exit 1
        sudo cp -r logs/ ${DESTDIR}/YellowHammer/YellowHammer-Server/
        sudo cp -r yellowhammer-db/ ${DESTDIR}/YellowHammer/YellowHammer-Server
        cd ${YHSERVERHOME}/yellowhammer-base || exit 1
        sudo cp -r logs ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/
        sudo cp config-ext.properties ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/
        sudo cp ./webapps/ROOT.war ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/

        ##checking for heapdump
        for f in ${YHSERVERHOME}/heapdump/*.hprof; do
            if [ -e "$f" ]; then
                printf "\t [!] Heapdump was captured by YellowHammer-Server. \n"
                sudo cp -r ${YHSERVERHOME}/heapdump ${DESTDIR}/YellowHammer/YellowHammer-Server/
            else
                printf "\t [#] No heapdump was generated by YellowHammer-Server. \n"
            fi
            break
        done
        #YellowHammer-WebClient collection
        echo "[+] Collecting YellowHammer-WebClient files"
        sudo -u sigmastream mkdir -p ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
        cd ${YHWEBCLIENTHOME} || exit 1
        sudo cp -r logs/ ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
        sudo cp -r config/ ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
        sudo cp yh-webclient.jar ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
        sudo tar czf webapp.tar.gz webapp/
        sudo mv webapp.tar.gz ${DESTDIR}/YellowHammer/YellowHammer-WebClient/

        #checking for heapdump
        for f in ${YHWEBCLIENTHOME}/heapdump/*.hprof; do
            if [ -e "$f" ]; then
                printf "\t [!] Heapdump was captured by YellowHammer-WebClient. \n"
                sudo cp -r ${YHWEBCLIENTHOME}/heapdump ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
            else
                printf "\t [#] No heapdump was generated by YellowHammer-WebClient.\n"
            fi
            break
        done

        echo "[+] Compressing final files"
        cd ${DESTDIR} || exit 1
        sudo tar czf YellowHammer-Support-$DATETIME.tar.gz YellowHammer
        sudo rm -rf YellowHammer/
        echo "[#] Please find troubleshoot bundle at ${DESTDIR}/YellowHammer-Support-$DATETIME.tar.gz"
        sudo chown -R sigmastream:sigmastream ${DESTDIR}
    else
        echo "[!] Please make sure ${YHSERVERHOME} and ${YHWEBCLIENTHOME} exists."
    fi
}

redcanary() {
        if [ -d "${RCAGENTHOME}" ]  && [ -d "${RCSERVERHOME}" ]; then 
            sudo chown -R sigmastream:sigmastream ${DESTDIR}
            echo "[+] Collecting RedCanary-Agent files"
            sudo -u sigmastream mkdir -p ${DESTDIR}/RedCanary/RedCanary-Agent
            cd ${RCAGENTHOME} || exit 1
            sudo cp -r logs/ ${DESTDIR}/RedCanary/RedCanary-Agent/
            sudo cp -r config/ ${DESTDIR}/RedCanary/RedCanary-Agent/
            sudo cp -r deploy/ ${DESTDIR}/RedCanary/RedCanary-Agent/
            sudo cp -r db/ ${DESTDIR}/RedCanary/RedCanary-Agent/
            sudo cp -r bin/ ${DESTDIR}/RedCanary/RedCanary-Agent/
            sudo cp -r data-files/ ${DESTDIR}/RedCanary/RedCanary-Agent/
            sudo cp rc-agent.jar ${DESTDIR}/RedCanary/RedCanary-Agent/
            
            ##checking for heapdump
            for f in ${RCAGENTHOME}/heapdump/*.hprof; do
                if [ -e "$f" ]; then
                    printf "\t [!] Heapdump was captured by RedCanary-Agent. \n"
                    sudo cp -r ${RCAGENTHOME}/heapdump ${DESTDIR}/RedCanary/RedCanary-Agent
                else
                    printf "\t [#] No heapdump was captured by RedCanary-Agent. \n"
                fi
                break
            done

            echo "[+] Collecting RedCanary-Server files"
            sudo -u sigmastream mkdir -p ${DESTDIR}/RedCanary/RedCanary-Server
            cd ${RCSERVERHOME} || exit 1
            sudo cp -r logs/ ${DESTDIR}/RedCanary/RedCanary-Server/
            sudo cp -r config/ ${DESTDIR}/RedCanary/RedCanary-Server/
            sudo cp -r db/ ${DESTDIR}/RedCanary/RedCanary-Server/
            sudo cp rc-server.jar ${DESTDIR}/RedCanary/RedCanary-Server/
            
            ##checking for heapdump
            for f in ${RCSERVERHOME}/heapdump/*.hprof; do
                if [ -e "$f" ]; then
                    printf "\t [!] Heapdump was captured by RedCanary-Server. \n"
                    sudo cp -r ${RCSERVERHOME}/heapdump ${DESTDIR}/RedCanary/RedCanary-Agent
                else
                    printf "\t [#] No heapdump was captured by RedCanary-Server. \n"
                fi
                break
            done

            echo "[+] Compressing final files"
            cd ${DESTDIR} || exit 1
            sudo tar czf RedCanary-Support-$DATETIME.tar.gz RedCanary
            sudo rm -rf RedCanary/
            echo "[#] Please find troubleshoot bundle at ${DESTDIR}/RedCanary-Support-$DATETIME.tar.gz "
            sudo chown -R sigmastream:sigmastream ${DESTDIR}
        else
            echo "[!] Please make sure directory ${RCAGENTHOME} and ${RCSERVERHOME} exists."
        fi
}

bluecardinal(){
        if [ -d "${BCHOME}" ]; then 
            sudo chown -R sigmastream:sigmastream ${DESTDIR}
            echo "[+] Collecting BlueCardinal files"
            sudo -u sigmastream mkdir -p ${DESTDIR}/BlueCardinal/bin
            cd ${BCHOME} || exit 1
            sudo cp -r logs/ ${DESTDIR}/BlueCardinal/
            sudo cp -r config/ ${DESTDIR}/BlueCardinal
            sudo cp bluecardinal-core.jar ${DESTDIR}/BlueCardinal/
            cd ${BCHOME}/bin || exit 1
            sudo cp *.sh ${DESTDIR}/BlueCardinal/bin
            
            ##checking for heapdump
            for f in ${BCHOME}/heapdump/*.hprof; do
                if [ -e "$f" ]; then
                    printf "\t [!] Heapdump was captured by BlueCardinal. \n"
                    sudo cp -r ${BCHOME}/heapdump ${DESTDIR}/BlueCardinal/
                else
                    printf "\t [#] No heapdump was captured by BlueCardinal. \n"
                fi
                break
            done
            echo "[+] Compressing final files"
            cd ${DESTDIR} || exit 1
            sudo tar czf BlueCardinal-Support-$DATETIME.tar.gz BlueCardinal
            sudo rm -rf BlueCardinal/
            echo "[#] Please find troubleshoot bundle at ${DESTDIR}/BlueCardinal-Support-$DATETIME.tar.gz"
            sudo chown -R sigmastream:sigmastream ${DESTDIR}
        else
            echo "[!] Please make sure directory ${BCHOME} exists."
        fi
}

case "$1" in
    yellowhammer)
	yellowhammer
	;;
    redcanary)
	redcanary
	;;
    bluecardinal)
	bluecardinal
	;;
    *)
	echo $"Usage: $0 {yellowhammer|redcanary|bluecardinal}"
	exit 1
esac

exit 0