#!/bin/bash
YHSERVERHOME=/sigmastream/yhserver
YHWEBCLIENTHOME=/sigmastream/yhwebclient
DESTDIR=/sigmastream/Tools/Troubleshooting
JAVA_TOOLS=$YHSERVERHOME/java/bin
DATETIME=$(echo $(date +%Y%m%d-%H%M%S))

yellowhammer() {
    if [ -d "${YHSERVERHOME}" ]; then 
        if [ ! -d ${DESTDIR} ]; then
            mkdir -p ${DESTDIR} > /dev/null 2>&1
        fi
        #Generate heapdump
        

        ##

        sudo chown -R sigmastream:sigmastream ${DESTDIR}
        echo "[+] Collecting YellowHammer-Server files"
        sudo -u sigmastream mkdir -p ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/
        cd ${YHSERVERHOME} || exit 1
        sudo cp -r logs/ ${DESTDIR}/YellowHammer/YellowHammer-Server/
        sudo cp -r yellowhammer-db/ ${DESTDIR}/YellowHammer/YellowHammer-Server
        cd ${YHSERVERHOME}/yellowhammer-base || exit 1
        sudo cp -r logs ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/
        sudo cp config-ext.properties ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/
        sudo cp ./webapps/ROOT.war ${DESTDIR}/YellowHammer/YellowHammer-Server/yellowhammer-base/

        ##checking for heapdump
            for f in ${YHSERVERHOME}/heapdump/*.hprof; do
                if [ -e "$f" ]; then
                    printf "\t [!] Heapdump was captured by YellowHammer-Server. \n"
                    sudo cp -r ${YHSERVERHOME}/heapdump ${DESTDIR}/YellowHammer/YellowHammer-Server/
                else
                    printf "\t [#] No heapdump was generated by YellowHammer-Server. \n"
                fi
                break
            done
        else
            echo "[!] Unable to open ${YHWEBCLIENTHOME}"
            echo "[#] Seems like YellowHammer-Server isn't installed."
        fi
        #YellowHammer-WebClient collection
        if [ -d "${YHWEBCLIENTHOME}" ]; then
            echo "[+] Collecting YellowHammer-WebClient files"
            sudo -u sigmastream mkdir -p ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
            cd ${YHWEBCLIENTHOME} || exit 1
            sudo cp -r logs/ ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
            sudo cp -r config/ ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
            sudo cp yh-webclient.jar ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
            sudo tar czf webapp.tar.gz webapp/
            sudo mv webapp.tar.gz ${DESTDIR}/YellowHammer/YellowHammer-WebClient/

            #checking for heapdump
            for f in ${YHWEBCLIENTHOME}/heapdump/*.hprof; do
                if [ -e "$f" ]; then
                    printf "\t [!] Heapdump was captured by YellowHammer-WebClient. \n"
                    sudo cp -r ${YHWEBCLIENTHOME}/heapdump ${DESTDIR}/YellowHammer/YellowHammer-WebClient/
                else
                    printf "\t [#] No heapdump was generated by YellowHammer-WebClient.\n"
                fi
                break
            done
        else
            echo "[!] Unable to open ${YHWEBCLIENTHOME}"
            echo "[#] Seems like YellowHammer-WebClient isn't installed."
        fi
        echo "[+] Compressing final files"
        cd ${DESTDIR} || exit 1
        sudo tar czf YellowHammer-Support-$DATETIME.tar.gz YellowHammer
        sudo rm -rf YellowHammer/
        echo "[#] Please find troubleshoot bundle at ${DESTDIR}/YellowHammer-Support-$DATETIME.tar.gz"
        sudo chown -R sigmastream:sigmastream ${DESTDIR}

}

case "$1" in
    yellowhammer)
	yellowhammer
	;;
    *)
	echo $"Usage: $0 yellowhammer"
	exit 1
esac
exit 0